name: Push commit
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: date +%s > report.txt
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Commit report
        run: |
          npm install
          mv package.json old_package.json
          ls
          pwd
          git init
          git add node_modules old_package.json
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "Automated report"
          git push
